apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: smflx71tp-go
  janus-idp.io/tekton: smflx71tp-go
  backstage.io/kubernetes-id: smflx71tp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: smflx71tp-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
